# SPDX-FileCopyrightText: Common Ground Electronics <https://cgnd.dev>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

baseURL = "https://cgnd.dev"
title = "cgnd.dev"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
pagination.pagerSize = 20
enableEmoji = true
enableGitInfo = true

[params]
author = "Common Ground Electronics"
license = ""
licenseURL = "https://github.com/cgnd/cgnd.dev/blob/main/LICENSE.md"
description = "Common Ground Electronics"
keywords = ""
# info = ["Coming soon..."]
avatarURL = "images/logo.svg"
# gravatar = "gravatar@cgnd.dev"
dateFormat = "January 2, 2006"
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/cgnd/cgnd.dev/tree"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []
mask_icon_color = "black"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/"
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/"
# ]
# prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/cgnd"

[[params.social]]
name = "Bluesky"
icon = "fa-brands fa-bluesky fa-2x"
weight = 2
url = "https://bsky.app/profile/cgnd.dev"
rel = "me"

[[params.social]]
name = "Mastodon"
icon = "fa-brands fa-mastodon fa-2x"
weight = 3
url = "https://mastodon.social/@cgnd"
rel = "me"

[[params.social]]
name = "X (Twitter)"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 4
url = "https://x.com/cgndelectronics"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 5
url = "https://www.linkedin.com/company/common-ground-electronics/"

[[params.social]]
name = "RSS"
icon = "fa fa-rss fa-2x"
weight = 6
url = "https://cgnd.dev/index.xml"
rel = "alternate"
type = "application/rss+xml"

[[menu.main]]
name = "About"
weight = 1
url = "about/"

# [[menu.main]]
# name = "Services"
# weight = 2
# url = "services/"

# [[menu.main]]
# name = "Portfolio"
# weight = 3
# url = "portfolio/"

[[menu.main]]
name = "Blog"
weight = 4
url = "posts/"

[[menu.main]]
name = "Contact"
weight = 5
url = "contact/"

[params.giscus]
repo = "cgnd/cgnd.dev"
repoID = "R_kgDOIcblIw"
category = "Blog Posts"
categoryID = "DIC_kwDOIcblI84CX7an"
mapping = "og:title"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
theme = "preferred_color_scheme"
lang = "en"
loading = "lazy"

[markup.highlight]
style = 'monokai'
