# SPDX-FileCopyrightText: Common Ground Electronics <https://cgnd.dev>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.128.0"
